const accidentals = {
  DBLFLAT: "♭♭",
  FLAT: "♭",
  NATR: "♮",
  SHRP: "♯",
  DBLSHRP: "♯♯",
};

const exerciseTypes = {
  CHORD: 0,
  SCALE: 1,
};

const bareNames = ["C", "D", "E", "F", "G", "A", "B"];

const notes = [
  {
    B: accidentals.SHRP,
    C: accidentals.NATR,
    D: accidentals.DBLFLAT,
  },
  {
    B: accidentals.DBLSHRP,
    C: accidentals.SHRP,
    D: accidentals.FLAT,
  },
  {
    C: accidentals.DBLSHRP,
    D: accidentals.NATR,
    E: accidentals.DBLFLAT,
  },
  {
    D: accidentals.SHRP,
    E: accidentals.FLAT,
    F: accidentals.DBLFLAT,
  },
  {
    D: accidentals.DBLSHRP,
    E: accidentals.NATR,
    F: accidentals.FLAT,
  },
  {
    E: accidentals.SHRP,
    F: accidentals.NATR,
    G: accidentals.DBLFLAT,
  },
  {
    E: accidentals.DBLSHRP,
    F: accidentals.SHRP,
    G: accidentals.FLAT,
  },
  {
    F: accidentals.DBLSHRP,
    G: accidentals.NATR,
    A: accidentals.DBLFLAT,
  },
  {
    G: accidentals.SHRP,
    A: accidentals.FLAT,
  },
  {
    G: accidentals.DBLSHRP,
    A: accidentals.NATR,
    B: accidentals.DBLFLAT,
  },
  {
    A: accidentals.SHRP,
    B: accidentals.FLAT,
    C: accidentals.DBLFLAT,
  },
  {
    A: accidentals.DBLSHRP,
    B: accidentals.NATR,
    C: accidentals.FLAT,
  },
];

const manepuRoots = [
  "ma",
  "ne",
  "pu",
  "qa",
  "re",
  "su",
  "ta",
  "ve",
  "wu",
  "xa",
  "ye",
  "zu",
];

const roots = {
  C: 0,
  "C♯": 1,
  "D♭": 1,
  D: 2,
  "D♯": 3,
  "E♭": 3,
  E: 4,
  F: 5,
  "F♯": 6,
  "G♭": 6,
  G: 7,
  "G♯": 8,
  "A♭": 8,
  A: 9,
  "A♯": 10,
  "B♭": 10,
  B: 11,
};

const chords = {
  maj: [0, 4, 7],
  min: [0, 3, 7],
  "min 7": [0, 3, 7, 10],
  "maj 7": [0, 4, 7, 11],
  // "maj 9": [],
  // aug: [],
  // dim: [],
  // "maj 11": [],
  // "ma 13": [],
  // "maj9#11": [],
  // "6": [],
  // add9: [],
  // "6add9": [],
  // maj7b5: [],
  // "maj7#5": [],
  // "min 9": [],
  // "min 11": [],
  // "min 13": [],
  // "min 6": [],
  // "min add9": [],
  // "min6 add9": [],
  // "min maj7": [],
  // "min maj9": [],
  // min7b5: [],
  // "min7#5": [],
  // "7": [],
  // "9": [],
  // "11": [],
  // "13": [],
  // "7sus4": [],
  // "7b5": [],
  // "7#5": [],
  // "7b9": [],
  // "7#9": [],
  // "7(b5,b9)": [],
  // "7(b5,#9)": [],
  // "7(#5,b9)": [],
  // "7(#5,#9)": [],
  // "9b5": [],
  // "9#5": [],
  // "13#11": [],
  // "13b9": [],
  // "11b9": [],
  // "dim 7": [],
  // "5": [],
  // sus4: [],
  // sus2: [],
  // sus2sus4: [],
  // "-5": [],
};
const scales = {
  major: [0, 2, 4, 5, 7, 9, 11],
  "natural minor": [0, 2, 3, 5, 7, 8, 10],
  // ionian: undefined,
  // dorian: undefined,
  // phrygian: undefined,
  // lydian: undefined,
  // mixolydian: undefined,
  // aeolian: undefined,
  // locrian: undefined,
  // "harmonic minor": undefined,
  // "melodic minor": undefined,
  // "whole tone": undefined,
  // "phrygian dominant": undefined,
  // "pentatonic major": undefined,
  // "pentatonic minor": undefined,
  // "blues major": undefined,
  // "blues minor": undefined,
};
export { exerciseTypes, roots, chords, scales, accidentals, notes, bareNames };
